// <auto-generated />
using L2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L2.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20260530071146_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L2.Models.AnimeCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("AnimeCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 17,
                            Description = "Ниндзя.",
                            ImageUrl = "https://i1-c.pinimg.com/736x/85/2c/88/852c880e20debd8b1ed40b1ce53aa250.jpg",
                            Name = "Наруто Узумаки",
                            StudioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            Description = "Сайян, защищающий Землю.",
                            ImageUrl = "https://i.pinimg.com/736x/e1/c4/d1/e1c4d1af1e67fa17ffa976df8285fcfc.jpg",
                            Name = "Гоку",
                            StudioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            Description = "Гениальный школьник, нашедший тетрадь смерти.",
                            ImageUrl = "https://i.pinimg.com/736x/02/c1/11/02c11137c640b5a14e8428308a0a56ba.jpg",
                            Name = "Лайт Ягами",
                            StudioId = 3
                        });
                });

            modelBuilder.Entity("L2.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Япония",
                            FoundedYear = 1979,
                            Name = "Pierrot"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Япония",
                            FoundedYear = 1948,
                            Name = "Toei Animation"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Япония",
                            FoundedYear = 1972,
                            Name = "Madhouse"
                        });
                });

            modelBuilder.Entity("L2.Models.AnimeCharacter", b =>
                {
                    b.HasOne("L2.Models.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });
#pragma warning restore 612, 618
        }
    }
}
